"""Repository interfaces — declared in the domain, implemented in persistence.

These Protocols are the seam Clean Architecture requires: outer layers (ingestion,
api) depend on *these interfaces*, and ``coffer.persistence`` supplies the concrete
SQLAlchemy-backed implementations. The dependency therefore points inward — the
domain never imports persistence (import-linter enforces this).

Each ``add`` returns the entity with its assigned ``id``. Lookups return ``None``
when nothing matches. Methods here are only those the downstream slices actually
need (dedup lookups, account/credential resolution, snapshot upsert); queries are
added slice-by-slice, not speculatively.
"""

from __future__ import annotations

import datetime
from typing import Protocol

from coffer.domain.entities import (
    Account,
    Category,
    Holding,
    Household,
    InstitutionCredential,
    LearnedRule,
    Member,
    NetworthSnapshot,
    Override,
    Statement,
    Transaction,
)


class HouseholdRepo(Protocol):
    def add(self, household: Household) -> Household: ...
    def get(self, household_id: int) -> Household | None: ...
    def by_name(self, name: str) -> Household | None: ...


class MemberRepo(Protocol):
    def add(self, member: Member) -> Member: ...
    def get(self, member_id: int) -> Member | None: ...
    def by_telegram_user_id(self, telegram_user_id: int) -> Member | None: ...
    def list_by_household(self, household_id: int) -> list[Member]: ...


class AccountRepo(Protocol):
    def add(self, account: Account) -> Account: ...
    def get(self, account_id: int) -> Account | None: ...
    def by_number_masked(self, account_number_masked: str) -> Account | None: ...
    def list_by_household(self, household_id: int) -> list[Account]: ...


class InstitutionCredentialRepo(Protocol):
    def add(self, credential: InstitutionCredential) -> InstitutionCredential: ...
    def get(self, credential_id: int) -> InstitutionCredential | None: ...
    def by_household_institution(
        self, household_id: int, institution: str
    ) -> InstitutionCredential | None: ...


class StatementRepo(Protocol):
    def add(self, statement: Statement) -> Statement: ...
    def get(self, statement_id: int) -> Statement | None: ...
    def by_file_hash(self, file_hash: str) -> Statement | None: ...  # dedup layer 1
    def by_content_hash(self, content_hash: str) -> Statement | None: ...  # dedup layer 2
    def list_by_account(self, account_id: int) -> list[Statement]: ...


class TransactionRepo(Protocol):
    def add(self, transaction: Transaction) -> Transaction: ...
    def get(self, transaction_id: int) -> Transaction | None: ...
    def by_dedup_key(self, dedup_key: str) -> Transaction | None: ...  # dedup layer 3
    def list_by_account(self, account_id: int) -> list[Transaction]: ...


class CategoryRepo(Protocol):
    def add(self, category: Category) -> Category: ...
    def get(self, category_id: int) -> Category | None: ...
    def list_by_household(self, household_id: int) -> list[Category]: ...


class OverrideRepo(Protocol):
    def add(self, override: Override) -> Override: ...
    def list_by_transaction(self, transaction_id: int) -> list[Override]: ...


class LearnedRuleRepo(Protocol):
    def add(self, rule: LearnedRule) -> LearnedRule: ...
    def get(self, rule_id: int) -> LearnedRule | None: ...
    def list_active_by_household(self, household_id: int) -> list[LearnedRule]: ...
    # A learned rule that fires on ingest gets its usage counted (SPEC §3.3 — surfaces
    # which rules earn their keep). The bump is the ingest orchestrator's job (S9).
    def bump_hit_count(self, rule_id: int, *, by: int = 1) -> None: ...


class HoldingRepo(Protocol):
    def add(self, holding: Holding) -> Holding: ...
    def list_by_statement(self, statement_id: int) -> list[Holding]: ...


class NetworthSnapshotRepo(Protocol):
    def upsert(self, snapshot: NetworthSnapshot) -> NetworthSnapshot: ...
    def by_grid(self, household_id: int, grid_date: datetime.date) -> NetworthSnapshot | None: ...
    def list_by_household(self, household_id: int) -> list[NetworthSnapshot]: ...
