"""S4: SPEC section 2 persistence model

Revision ID: 1764a988dedb
Revises: 
Create Date: 2026-07-13 01:30:50.434819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1764a988dedb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('match_pattern', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('cadence', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_household_id'), 'category', ['household_id'], unique=False)
    op.create_table('institution_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=50), nullable=False),
    sa.Column('password_scheme', sa.String(length=20), nullable=False),
    sa.Column('password_enc', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_credential_household_id'), 'institution_credential', ['household_id'], unique=False)
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id')
    )
    op.create_index(op.f('ix_member_household_id'), 'member', ['household_id'], unique=False)
    op.create_table('networth_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('grid_date', sa.Date(), nullable=False),
    sa.Column('cash_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit_liability_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('portfolio_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'grid_date', name='uq_snapshot_grid')
    )
    op.create_index(op.f('ix_networth_snapshot_grid_date'), 'networth_snapshot', ['grid_date'], unique=False)
    op.create_index(op.f('ix_networth_snapshot_household_id'), 'networth_snapshot', ['household_id'], unique=False)
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=50), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('account_number_masked', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_account_number_masked'), 'account', ['account_number_masked'], unique=True)
    op.create_index(op.f('ix_account_member_id'), 'account', ['member_id'], unique=False)
    op.create_table('statement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('uploaded_via', sa.String(length=20), nullable=False),
    sa.Column('uploaded_by_member_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('encrypted_file_path', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statement_account_id'), 'statement', ['account_id'], unique=False)
    op.create_index(op.f('ix_statement_content_hash'), 'statement', ['content_hash'], unique=True)
    op.create_index(op.f('ix_statement_file_hash'), 'statement', ['file_hash'], unique=True)
    op.create_table('holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('lot_balance', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('market_price', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unrealized_pl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['statement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holding_account_id'), 'holding', ['account_id'], unique=False)
    op.create_index(op.f('ix_holding_statement_id'), 'holding', ['statement_id'], unique=False)
    op.create_index(op.f('ix_holding_ticker'), 'holding', ['ticker'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_source', sa.String(length=20), nullable=True),
    sa.Column('counterparty_name', sa.Text(), nullable=True),
    sa.Column('counterparty_acct', sa.String(length=100), nullable=True),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('raw_ref', sa.Text(), nullable=False),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['edited_by'], ['member.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['statement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_account_id'), 'transaction', ['account_id'], unique=False)
    op.create_index(op.f('ix_transaction_counterparty_acct'), 'transaction', ['counterparty_acct'], unique=False)
    op.create_index(op.f('ix_transaction_date'), 'transaction', ['date'], unique=False)
    op.create_index(op.f('ix_transaction_dedup_key'), 'transaction', ['dedup_key'], unique=True)
    op.create_index(op.f('ix_transaction_statement_id'), 'transaction', ['statement_id'], unique=False)
    op.create_table('learned_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('match_counterparty_acct', sa.String(length=100), nullable=True),
    sa.Column('match_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('match_amount_tolerance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('created_from_transaction_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['created_from_transaction_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learned_rule_household_id'), 'learned_rule', ['household_id'], unique=False)
    op.create_index(op.f('ix_learned_rule_match_counterparty_acct'), 'learned_rule', ['match_counterparty_acct'], unique=False)
    op.create_table('override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_override_transaction_id'), 'override', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_override_transaction_id'), table_name='override')
    op.drop_table('override')
    op.drop_index(op.f('ix_learned_rule_match_counterparty_acct'), table_name='learned_rule')
    op.drop_index(op.f('ix_learned_rule_household_id'), table_name='learned_rule')
    op.drop_table('learned_rule')
    op.drop_index(op.f('ix_transaction_statement_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_dedup_key'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_counterparty_acct'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_account_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_holding_ticker'), table_name='holding')
    op.drop_index(op.f('ix_holding_statement_id'), table_name='holding')
    op.drop_index(op.f('ix_holding_account_id'), table_name='holding')
    op.drop_table('holding')
    op.drop_index(op.f('ix_statement_file_hash'), table_name='statement')
    op.drop_index(op.f('ix_statement_content_hash'), table_name='statement')
    op.drop_index(op.f('ix_statement_account_id'), table_name='statement')
    op.drop_table('statement')
    op.drop_index(op.f('ix_account_member_id'), table_name='account')
    op.drop_index(op.f('ix_account_account_number_masked'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_networth_snapshot_household_id'), table_name='networth_snapshot')
    op.drop_index(op.f('ix_networth_snapshot_grid_date'), table_name='networth_snapshot')
    op.drop_table('networth_snapshot')
    op.drop_index(op.f('ix_member_household_id'), table_name='member')
    op.drop_table('member')
    op.drop_index(op.f('ix_institution_credential_household_id'), table_name='institution_credential')
    op.drop_table('institution_credential')
    op.drop_index(op.f('ix_category_household_id'), table_name='category')
    op.drop_table('category')
    op.drop_table('household')
    # ### end Alembic commands ###
